conf.py:
  copyright: '2011-2015, respective authors'
  project: 'TYPO3 Surf'
  version: 'master'
  release: 'master'
  latex_documents:
  - - Index
    - typo3.surf.tex
    - TYPO3 Surf Deployment Tool
    - TYPO3 Surf team
    - manual
  latex_use_parts: 'true'
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
